
Neos:
  Neos:
    userInterface:
      requireJsPathMapping:
        Sandstorm.ContentComments: 'resource://Sandstorm.ContentComments/Public/JavaScript/'
    fusion:
      autoInclude:
        Sandstorm.ContentComments: true
